name: example
description: An example of package:widget_view.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  widget_view:
    path: ../
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true