name: widget_view
description: A Dart package that supports for separation of logic and view in a widget.
version: 0.1.2
homepage: https://github.com/polyflection/widget_view

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0