name: widget_view
description: A Dart package that supports for separation of logic and view in a widget.
version: 0.3.0-nullsafety.0
homepage: https://github.com/polyflection/widget_view

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety.3